import type { Metadata } from 'next';

export const SITE_URL = 'https://coastalsurfacerestoration.com';
export const SITE_NAME = 'Coastal Surface Restoration';

export const BUSINESS = {
  name: 'Coastal Surface Restoration LLC',
  shortName: SITE_NAME,
  phone: '854-222-7790',
  email: 'tyler@coastalsurfacerestoration.com',
  region: 'Charleston, SC & Lowcountry',
  socials: [
    'https://www.instagram.com/coastalsurfacerestoration',
    'https://www.facebook.com/profile.php?id=61589821678350',
    'https://www.tiktok.com/@coastalsurfacesc',
  ],
} as const;

type PageMetaInput = {
  /** Bare title — the root layout appends "| Coastal Surface Restoration". */
  title: string;
  description: string;
  /** Root-relative path, e.g. '/services/rust-removal-charleston'. */
  path: string;
};

/**
 * The image generated by app/opengraph-image.tsx. Resolved against
 * `metadataBase` from the root layout.
 *
 * It has to be named explicitly: the opengraph-image file convention only
 * populates the segment that owns the file, and because metadata is shallow-
 * merged, a page defining its own `openGraph` replaces the parent's images
 * along with everything else. Pages that skip it end up with no og:image.
 */
const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'Coastal Surface Restoration, mobile laser cleaning in Charleston, SC',
};

/**
 * Metadata for a page, with the canonical and social tags filled in.
 *
 * Every page needs its own openGraph block for the reason above — a page that
 * only sets `title` would inherit the root layout's OG title verbatim. Building
 * it from the same title/description here keeps the two from drifting apart.
 */
export function pageMetadata({ title, description, path }: PageMetaInput): Metadata {
  const fullTitle = `${title} | ${SITE_NAME}`;

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      locale: 'en_US',
      siteName: SITE_NAME,
      url: path,
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
  };
}
